[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    nanopb/Nanopb

build_flags =
    -I../../proto/build/generated/sources/proto/main/nanopb
    -I$PROJECT_LIBDEPS_DIR/$PIOENV/Nanopb
    -D PB_ENABLE_MALLOC

extra_scripts =
    pre:scripts/generated_proto.py