[env:esp32dev]

platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    nanopb/Nanopb
    adafruit/Adafruit SSD1306

build_flags =
    -I../../proto/build/generated/sources/proto/nanopb/nanopb
    -D PB_ENABLE_MALLOC

extra_scripts =
    pre:scripts/generated_proto.py