syntax = "proto3";

package alarm_system.v1;

option java_package = "com.karstonn.alarmsystem.proto";
option java_multiple_files = true;
option java_outer_classname = "AlarmSystemProto";

// --------- Shared Domain Types ---------
enum DayOfWeek {
  DAY_UNSPECIFIED = 0;
  MONDAY = 1;
  TUESDAY = 2;
  WEDNESDAY = 3;
  THURSDAY = 4;
  FRIDAY = 5;
  SATURDAY = 6;
  SUNDAY = 7;
}

message RGB {
  uint32 r = 1;
  uint32 g = 2;
  uint32 b = 3;
}

message TimeOfDay {
  uint32 hour = 1;
  uint32 min = 2;
}

// -- Action Configs --
message TurnOnLight {
  RGB rgb = 2;
}

message SoundAlarm {
  string sound_id = 1;
  uint32 volume = 2;
}

// -- Action Wrapper --

message Action {
  string id = 1;
  string label = 2;
  string device_id = 3;
  oneof config{
    TurnOnLight turn_on_light = 4;
    SoundAlarm sound_alarm = 5;
  }
}

// -- Alarm Structure --
message AlarmId {
  string id = 1;
}

message AlarmPhaseId {
  AlarmId alarm_id = 1;
  string phase_id = 2;
}

message AlarmPhase{
  string phase_id = 1;
  TimeOfDay trigger_time = 2;
  string label = 3;
  repeated Action actions = 4;
}

message Alarm {
  AlarmId id = 1;
  string label = 2;
  repeated AlarmPhase alarm_phases = 3;
  repeated DayOfWeek days = 4;
  bool is_recurring = 5;
  bool is_enabled = 6;
}

// --------- Alarm Repo Service Request/Response ---------

message UpdateAlarmRequest{
  AlarmId id = 1;
  Alarm alarm = 2;
}

message AlarmRequestResponse{
  bool success = 1;
}

message AlarmListRequest {
  //empty
}

message AlarmListResponse {
  repeated Alarm alarms = 1;
}

// --------- Alarm Repo Service ---------

service AlarmRepoService {
  rpc GetAlarm(AlarmId) returns (Alarm);
  rpc AddAlarm(Alarm) returns (AlarmRequestResponse);
  rpc UpdateAlarm(UpdateAlarmRequest) returns (AlarmRequestResponse);
  rpc RemoveAlarm(AlarmId) returns (AlarmRequestResponse);
  rpc ListAlarms(AlarmListRequest) returns (AlarmListResponse);
}

// --------- Action Execution Service Request/Response ---------

message ActionExecutionRequest{
  AlarmPhaseId alarm_phase_id = 1;
  repeated Action actions = 2;
}

message ActionExecutionResult{
  string action_id = 1;
  bool success = 2;
  string message = 3;
}

message ActionExecutionsResponse{
  AlarmPhaseId alarm_phase_id = 1;
  repeated ActionExecutionResult results = 2;
}

// --------- Action Execution Service ---------

service ExecutionService {
  rpc TriggerAlarmActions(ActionExecutionRequest) returns (ActionExecutionsResponse);
}

// --------- Service Request/Response ---------

message SnoozeRequest {
  AlarmPhaseId alarm_phase_id = 1;
  uint32 snooze_mins = 2;
  string source_id = 3;
}
message SnoozeResponse {
  bool success = 1;
}

message DismissRequest {
  AlarmPhaseId alarm_phase_id = 1;
  string source_id = 2;
}
message DismissResponse {
  bool success = 1;
}

// --------- Service ---------

service AlarmRunTimeService {
    rpc SnoozeAlarm(SnoozeRequest) returns (SnoozeResponse);
    rpc DismissAlarm(DismissRequest) returns (DismissResponse);
}