syntax = "proto3";

package alarm_system.v1;

option java_package = "com.karstonn.alarmsystem.proto";
option java_multiple_files = true;
option java_outer_classname = "AlarmSystemProto";

// --------- Shared Domain Types ---------
enum DayOfWeek {
  DAY_UNSPECIFIED = 0;
  MONDAY = 1;
  TUESDAY = 2;
  WEDNESDAY = 3;
  THURSDAY = 4;
  FRIDAY = 5;
  SATURDAY = 6;
  SUNDAY = 7;
}

message RGBA {
  uint32 rgba = 1;
}

message Percentage {
  uint32 value = 1;
}

message FileData {
  string filename = 1;
  string file_type = 2;
  uint64 size_bytes = 3;
  //This is a potential issue for data bloat
  //e.g. multiple copies of a large audio file being stored
  bytes file_content = 4;
}

message TimeOfDay {
  uint32 hour = 1;
  uint32 min = 2;
}

// -- Action Configs --
// THIS MUST BE MANUALLY LINKED WITH ActionValueType!!
// no trick in protobuf to do this :(
message ActionValue {
  oneof value {
    string string_val = 1;
    uint32 uint32_val = 2;
    int32 int32_val = 3;
    bool bool_val = 4;
    RGBA rgba_val = 5;
    Percentage percentage = 6;
    FileData file = 7;
    double double_val = 8;
  }
}

message ActionParameter {
  string parameter_id = 1;
  string parameter_key = 2;
  string label = 3;
  ActionValue value = 4;
  optional string units = 5;

}

// -- Action Wrapper --

message ActionId {
  string action_id = 1;
}

message Action {
  ActionId id = 1;
  string label = 2;
  DeviceId deviceId = 3;
  //Specify action type on device
  //(i.e. one device may have multiple possible actions)
  DeviceCapabilityKey device_action_key = 4;
  repeated ActionParameter parameters = 5;
}

// -- Alarm Structure --
message AlarmId {
  string Alarm_id = 1;
}

message AlarmPhaseId {
  string phase_id = 1;
}

message AlarmPhase{
  AlarmPhaseId phase_id = 1;
  TimeOfDay trigger_time = 2;
  string label = 3;
  repeated Action actions = 4;
}

message Alarm {
  AlarmId id = 1;
  string label = 2;
  repeated AlarmPhase alarm_phases = 3;
  repeated DayOfWeek days = 4;
  bool is_recurring = 5;
  bool is_enabled = 6;
}

// --------- Alarm Repo Service Request/Response ---------

message UpdateAlarmRequest{
  AlarmId id = 1;
  Alarm alarm = 2;
}

message AddAlarmRequest {
  Alarm alarm = 1;
}
message AddAlarmResponse {
  bool success = 1;
  string msg = 2;
  AlarmId id = 3;
}

message AlarmRequestResponse{
  bool success = 1;
}

message AlarmListRequest {
  //empty
}

message AlarmListing {
  AlarmId id = 1;
  string label = 2;
  bool isEnabled = 3;
}

message AlarmListResponse {
  repeated  AlarmListing alarms = 1;
}

// --------- Alarm Repo Service ---------

service AlarmRepoService {
  rpc GetAlarm(AlarmId) returns (Alarm);
  rpc AddAlarm(AddAlarmRequest) returns (AddAlarmResponse);
  rpc UpdateAlarm(UpdateAlarmRequest) returns (AlarmRequestResponse);
  rpc RemoveAlarm(AlarmId) returns (AlarmRequestResponse);
  rpc ListAlarms(AlarmListRequest) returns (AlarmListResponse);
}

// --------- Controller ---------
// Controllers are responsible to execute device action
// But devices are independent - the controller responsible can be swapped
message ControllerId {
  string id = 1;
}

message Controller {
  ControllerId controller_id = 1;
  string label = 2;
}

// --------- Controller Repo Service Request/Response ---------

message GetControllerRequest {
  ControllerId controller_id =1;
}
message GetControllerResponse {
  bool success = 1;
  string msg = 2;
  optional Controller controller = 3;
}

message AddControllerRequest {
  Controller controller = 1;
}
message AddControllerResponse {
  bool success = 1;
  string msg = 2;
}

message UpdateControllerRequest {
  Controller controller = 1;
}
message UpdateControllerResponse {
  bool success = 1;
  string msg = 2;
}

message RemoveControllerRequest {
  ControllerId controller_id = 1;
}
message RemoveControllerResponse {
  bool success = 1;
  string msg = 2;
}

message ListControllersRequest {}
message ListControllersResponse {
  repeated Controller controllers = 1;
}

message RequestIDRequest {}
message RequestIDResponse {
  ControllerId controller_id= 1;
}


// --------- Controller Repo Service ---------
service ControllerRegistryService {
  rpc GetController(GetControllerRequest) returns (GetControllerResponse);
  rpc AddController(AddControllerRequest) returns (AddControllerResponse);
  rpc RemoveController(RemoveControllerRequest) returns (RemoveControllerResponse);
  rpc UpdateController(UpdateControllerRequest) returns (UpdateControllerResponse);
  rpc ListControllers(ListControllersRequest) returns (ListControllersResponse);
  rpc RequestUUID (RequestIDRequest) returns (RequestIDResponse);
}

// --------- Device Types ---------
// THIS MUST BE MANUALLY LINKED WITH ActionValue!!
// no trick in protobuf to do this :(

message StringRequirement{
  uint32 minLength = 1;
  uint32 maxLength = 2;
  bool AsciiOnly = 3;
}
message UINT32Requirement{
  uint32 minVal = 1;
  uint32 maxVal = 2;
}
message INT32Requirement{
  int32 minVal = 1;
  int32 maxVal = 2;
}
message BoolRequirement{}
message RGBARequirement{
  bool usesAlpha = 1;
}
message PercentageRequirement{
  uint32 minVal = 1;
  uint32 maxVal = 2;
  optional uint32 step = 3;
}
message FileRequirement{
  int32 maxSize = 1;
  string fileType = 2;
}
message DoubleRequirement{
  double minVal = 1;
  double maxVal = 2;
}

message DeviceId {
  string id = 1;
}

message DeviceCapabilityKey {
  string key = 1;
}

message ParameterRequirement {
  string key = 1;
  string label = 2;

  // THIS MUST BE MANUALLY LINKED WITH ActionValue!!
  // no trick in protobuf to do this :(
  oneof requirement {
    StringRequirement string_requirement = 11;
    UINT32Requirement uint32_requirement = 12;
    INT32Requirement int32_requirement = 13;
    BoolRequirement bool_requirement = 14;
    RGBARequirement rgba_requirement = 15;
    PercentageRequirement percentage_requirement = 16;
    FileRequirement file_requirement = 17;
    DoubleRequirement double_requirement = 18;
  }
}

message DeviceCapability {
  DeviceCapabilityKey key = 1;
  string label = 2;
  repeated ParameterRequirement parameter_requirements = 3;
}

message Device {
  ControllerId controller_id = 1;
  DeviceId device_id = 2;
  string label = 3;
  repeated DeviceCapability capabilities = 4;
}

// --------- Device Register Service Request/Response ---------

message AddDeviceRequest {
  Device device = 1;
  ControllerId controller_id = 2;
}

message UpdateDeviceRequest{
  Device device = 1;
}

message DeviceRequestResponse{
  bool success = 1;
}

message DeviceListRequest {
  //empty
}

message DeviceListResponse {
  repeated Device devices = 1;
}

// --------- Device Register Service ---------

service DeviceRegistryService{
  rpc GetDevice(DeviceId) returns (Device);
  rpc AddDevice(AddDeviceRequest) returns (DeviceRequestResponse);
  rpc UpdateDevice(UpdateDeviceRequest) returns (DeviceRequestResponse);
  rpc RemoveDevice(DeviceId) returns (DeviceRequestResponse);
  rpc ListDevices(DeviceListRequest) returns (DeviceListResponse);
}

// --------- Storage ---------
message AlarmStorage {
  repeated Alarm alarms = 1;
}

message DeviceStorage {
  repeated Device devices = 1;
}

message ControllerStorage {
  repeated Controller controllers = 1;
}